# Generated by Django 6.1 on 2026-08-24 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
