# Generated by Django 6.1 on 2026-08-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0002_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_TRIP', 'On Trip'), ('OFFLINE', 'Offline')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_name',
            field=models.CharField(blank=True, default='Toyota Camry Hybrid', max_length=100, null=True),
        ),
    ]
